### ISSUE TITLE
Return type deprecation when using PHP 8

### ISSUE THREAD

**Issue by adamsokolowski06** [centarro/kco_rest_php#3]
**Describe the bug**
Using the module with PHP 8.1 gives us a warning about deprecation:
```
Deprecated function: Return type of Klarna\Rest\Resource::exchangeArray($array) should either be compatible with
ArrayObject::exchangeArray(object|array $array): array, or the #[\ReturnTypeWillChange] attribute should be used to temporarily
suppress the notice in include()
```

**Which service do you use**
Klarna Checkout

**To Reproduce**
1. Use PHP 8.1 on the project
2. Create new Order instance

**Expected behavior**
The warning should not appear

**Additional context**
Using PHP 8.1

**Comment by eiriksm** [comment]
I believe this should be fixed in the latest version
